/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptchaStopRouteImport } from './routes/captcha.stop'
import { Route as CaptchaRhythmRouteImport } from './routes/captcha.rhythm'
import { Route as CaptchaGolfRouteImport } from './routes/captcha.golf'
import { Route as CaptchaEthosRouteImport } from './routes/captcha.ethos'
import { Route as CaptchaEmotionRouteImport } from './routes/captcha.emotion'
import { Route as CaptchaCounterRouteImport } from './routes/captcha.counter'

const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaStopRoute = CaptchaStopRouteImport.update({
  id: '/captcha/stop',
  path: '/captcha/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaRhythmRoute = CaptchaRhythmRouteImport.update({
  id: '/captcha/rhythm',
  path: '/captcha/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaGolfRoute = CaptchaGolfRouteImport.update({
  id: '/captcha/golf',
  path: '/captcha/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaEthosRoute = CaptchaEthosRouteImport.update({
  id: '/captcha/ethos',
  path: '/captcha/ethos',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaEmotionRoute = CaptchaEmotionRouteImport.update({
  id: '/captcha/emotion',
  path: '/captcha/emotion',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaCounterRoute = CaptchaCounterRouteImport.update({
  id: '/captcha/counter',
  path: '/captcha/counter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/complete': typeof CompleteRoute
  '/captcha/counter': typeof CaptchaCounterRoute
  '/captcha/emotion': typeof CaptchaEmotionRoute
  '/captcha/ethos': typeof CaptchaEthosRoute
  '/captcha/golf': typeof CaptchaGolfRoute
  '/captcha/rhythm': typeof CaptchaRhythmRoute
  '/captcha/stop': typeof CaptchaStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/complete': typeof CompleteRoute
  '/captcha/counter': typeof CaptchaCounterRoute
  '/captcha/emotion': typeof CaptchaEmotionRoute
  '/captcha/ethos': typeof CaptchaEthosRoute
  '/captcha/golf': typeof CaptchaGolfRoute
  '/captcha/rhythm': typeof CaptchaRhythmRoute
  '/captcha/stop': typeof CaptchaStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/complete': typeof CompleteRoute
  '/captcha/counter': typeof CaptchaCounterRoute
  '/captcha/emotion': typeof CaptchaEmotionRoute
  '/captcha/ethos': typeof CaptchaEthosRoute
  '/captcha/golf': typeof CaptchaGolfRoute
  '/captcha/rhythm': typeof CaptchaRhythmRoute
  '/captcha/stop': typeof CaptchaStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/complete'
    | '/captcha/counter'
    | '/captcha/emotion'
    | '/captcha/ethos'
    | '/captcha/golf'
    | '/captcha/rhythm'
    | '/captcha/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/complete'
    | '/captcha/counter'
    | '/captcha/emotion'
    | '/captcha/ethos'
    | '/captcha/golf'
    | '/captcha/rhythm'
    | '/captcha/stop'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/complete'
    | '/captcha/counter'
    | '/captcha/emotion'
    | '/captcha/ethos'
    | '/captcha/golf'
    | '/captcha/rhythm'
    | '/captcha/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CompleteRoute: typeof CompleteRoute
  CaptchaCounterRoute: typeof CaptchaCounterRoute
  CaptchaEmotionRoute: typeof CaptchaEmotionRoute
  CaptchaEthosRoute: typeof CaptchaEthosRoute
  CaptchaGolfRoute: typeof CaptchaGolfRoute
  CaptchaRhythmRoute: typeof CaptchaRhythmRoute
  CaptchaStopRoute: typeof CaptchaStopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/stop': {
      id: '/captcha/stop'
      path: '/captcha/stop'
      fullPath: '/captcha/stop'
      preLoaderRoute: typeof CaptchaStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/rhythm': {
      id: '/captcha/rhythm'
      path: '/captcha/rhythm'
      fullPath: '/captcha/rhythm'
      preLoaderRoute: typeof CaptchaRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/golf': {
      id: '/captcha/golf'
      path: '/captcha/golf'
      fullPath: '/captcha/golf'
      preLoaderRoute: typeof CaptchaGolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/ethos': {
      id: '/captcha/ethos'
      path: '/captcha/ethos'
      fullPath: '/captcha/ethos'
      preLoaderRoute: typeof CaptchaEthosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/emotion': {
      id: '/captcha/emotion'
      path: '/captcha/emotion'
      fullPath: '/captcha/emotion'
      preLoaderRoute: typeof CaptchaEmotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha/counter': {
      id: '/captcha/counter'
      path: '/captcha/counter'
      fullPath: '/captcha/counter'
      preLoaderRoute: typeof CaptchaCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CompleteRoute: CompleteRoute,
  CaptchaCounterRoute: CaptchaCounterRoute,
  CaptchaEmotionRoute: CaptchaEmotionRoute,
  CaptchaEthosRoute: CaptchaEthosRoute,
  CaptchaGolfRoute: CaptchaGolfRoute,
  CaptchaRhythmRoute: CaptchaRhythmRoute,
  CaptchaStopRoute: CaptchaStopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
